# Generated by Django 4.2.11 on 2026-03-27 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='residences.residence'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='listings_price_e6fc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['room_type'], name='listings_room_ty_e52efd_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['availability'], name='listings_availab_aa8956_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['is_featured'], name='listings_is_feat_01aa9f_idx'),
        ),
    ]
