# Generated by Django 3.1.7 on 2025-11-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210906_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discounted_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(),
        ),
    ]
