# Generated by Django 4.2.11 on 2026-03-28 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('lifestyle', 'Lifestyle'), ('cleanliness', 'Cleanliness'), ('schedule', 'Schedule'), ('social', 'Social'), ('study', 'Study Habits')], max_length=20)),
                ('options', models.JSONField(help_text='List of answer options, e.g. ["Early bird","Night owl"]')),
                ('weight', models.FloatField(default=1.0, help_text='Importance weight for matching score')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compatibility_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='matching.compatibilityquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_answers',
                'unique_together': {('student', 'question')},
            },
        ),
        migrations.CreateModel(
            name='RoommateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField(help_text='Score from 0.0 to 1.0')),
                ('breakdown', models.JSONField(blank=True, default=dict, help_text='Per-category score breakdown')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roommate_matches', to='listings.listing')),
                ('student_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to=settings.AUTH_USER_MODEL)),
                ('student_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roommate_matches',
                'ordering': ['-compatibility_score'],
                'unique_together': {('listing', 'student_a', 'student_b')},
            },
        ),
    ]
