# Generated by Django 4.2.11 on 2026-03-27 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='amenity',
            name='residences',
            field=models.ManyToManyField(blank=True, related_name='amenities', to='residences.residence'),
        ),
    ]
