# Generated by Django 5.2.7 on 2026-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='virtual_tour_video',
            field=models.FileField(blank=True, null=True, upload_to='residences/videos/'),
        ),
    ]
