# Generated by Django 5.2.7 on 2026-03-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0003_residence_virtual_tour_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='total_beds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='residence',
            name='total_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
